export const CURRENT_USER_FETCHED = 'CURRENT_USER_FETCHED';
export const CURRENT_USER_LOADING = 'CURRENT_USER_LOADING';
export const CURRENT_POPUP_SET = 'CURRENT_POPUP_SET';
export const LOCAL_STREEM_SET = 'LOCAL_STREEM_SET';
export const REMOTE_STREEM_SET = 'REMOTE_STREEM_SET';
export const CURRENT_TERMINAL_FETCHED = 'CURRENT_TERMINAL_FETCHED';
export const TERMINALS_FETCHED = 'TERMINALS_FETCHED';
export const CURRENT_FILE_SET = 'CURRENT_FILE_SET';