export const CURRENT_EMITTER_SET = 'CURRENT_EMITTER_SET';
export const CURRENT_EMITTER_ERROR = 'CURRENT_EMITTER_ERROR';
export const CURRENT_EMITTER_CREATING = 'CURRENT_EMITTER_CREATING';
export const CURRENT_PEER_SET = 'CURRENT_PEER_SET';
export const CURRENT_EVENTS_FETCHED = 'CURRENT_EVENTS_FETCHED';
export const SET_SHARE_EVENTS = 'SET_SHARE_EVENTS';
export const CURRENT_SELECTED_EVENT = 'CURRENT_SELECTED_EVENT';